Repository TACC/Core-CMS, pull requests merged in 2023-11, with the labels that each got.

#736 Feat/tup-632: django.cms.picture.css to core-cms
  taccsite_cms/static/site_cms/css/src/_imports/components/django.cms.picture.css
Labels: feature, migrate css to core

#737 feat/tup-633: Migrate lightgallery to core-cms
  taccsite_cms/static/site_cms/css/src/_imports/components/lightgallery.css
Labels: feature, migrate css to core

#738 feat/tup-634: Migrate pseudo-elements to core-cms
  taccsite_cms/static/site_cms/css/src/_imports/generics/pseudo-elements.css
  taccsite_cms/static/site_cms/css/src/core-cms.css
Labels: feature, migrate css to core

#743 feat: wp-333 SEARCH_PATH setting
  taccsite_cms/settings.py
  taccsite_cms/templates/nav_search.raw.html
Labels: feature

#678 feat: bump core-styles & use its django-cms-forms
  package-lock.json
  package.json
  taccsite_cms/static/djangocms_forms/css/djangocms_forms.css
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms--errors-via-c-message.css
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms.css
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms.hacks.css
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms/config.yml
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms/django-cms-forms.hbs
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms/readme.md
Labels: feature

#753 feat: update core-styles from v2.11 to v2.22 - misc bugs
  package-lock.json
  package.json
  taccsite_cms/static/site_cms/css/src/_imports/components/c-button.css
Labels: bug

#742 feat: update core-styles from v2.11 to v2.22
  package-lock.json
  package.json
  taccsite_cms/static/site_cms/css/src/_imports/components/c-button.css
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms--errors-via-c-message.css
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms.css
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms.hacks.css
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms/config.yml
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms/django-cms-forms.hbs
  taccsite_cms/static/site_cms/css/src/_imports/components/django-cms-forms/readme.md
Labels: priority ▲
